language: C
#sudo: required


before_install:
- brew update
- brew install clang-omp
  
os:
- osx
  compiler: clang-omp
- linux
  compiler: gcc
  dist: trusty
  sudo: required
      
script:
#- brew update
#- brew install clang-omp
- make -C src
- cd src
- ./test

depth: 1
